### ISSUE TITLE
Symphony Fatal Error: email is already subscribed to the list.

### ISSUE THREAD

**Issue by cmnstmntmn** [lewiswharf/mailchimp#17]
![error](https://cloud.githubusercontent.com/assets/2312755/6276663/280a5f52-b891-11e4-9218-059726ca6447.jpg)

**Comment by nitriques** [comment]
Hum... Which Symphony version ? And which extension version ?

**Comment by cmnstmntmn** [comment]
* Symphony **2.5.2**
* MailChimp **2.1.1**

also it was an error in **event.mailchimp.php** on line 7 at this declaration:

*use Drewm\MailChimp;*  --> error in the image
![error2](https://cloud.githubusercontent.com/assets/2312755/6277018/a2d35c32-b893-11e4-8757-6b7c94abf252.png)


i am running PHP Version 5.6.2

anyway i fixed it by removing **Drewm**

**Comment by nitriques** [comment]
Can you

1. Add a `try {` thing before this line https://github.com/lewiswharf/mailchimp/blob/master/events/event.mailchimp.php#L122
2. Add the following code after this line https://github.com/lewiswharf/mailchimp/blob/master/events/event.mailchimp.php#L188

```php
}
catch (Exception $ex) {
   $error = new XMLElement('error', General::wrapInCDATA($ex->getMessage()));
   $result->appendChild($error);
}
```

**Comment by cmnstmntmn** [comment]
it works, thank you :)

**Comment by nitriques** [comment]
My pleasure. :smile: Please send PR if you have time :)

**Comment by cmnstmntmn** [comment]
i have time, but no ideea about what PR means :D

**Comment by nitriques** [comment]
PR = Pull Request :smile:

**Comment by cmnstmntmn** [comment]
oh, yeah, right. i did it :d
