### ISSUE TITLE
Symphony Fatal Error: Class 'Drewm\MailChimp' not found

### ISSUE THREAD

**Issue by cmnstmntmn** [lewiswharf/mailchimp#18]
* SymphonyCMS **2.5.2**
* MailChimp **2.1.1**

in **event.mailchimp.php** on line 7 at this declaration:

*use Drewm\MailChimp;*  --> error in the image
![error2](https://cloud.githubusercontent.com/assets/2312755/6277018/a2d35c32-b893-11e4-8757-6b7c94abf252.png)

i am running PHP Version 5.6.2

anyway i fixed it by removing **Drewm**

**Comment by wdebusschere** [comment]
Symphony 2.6.7

Symphony Warning: The use statement with non-compound name 'MailChimp' has no effect

> An error occurred in /Users/xxx/Sites/xxx/extensions/mailchimp/events/event.mailchimp.php around line 7

**Comment by nitriques** [comment]
Still PHP5.6 ? I needed it for PHP 5.3... But I do not use 5.3 any more, so I think we can 100% remove it.
