### ISSUE TITLE
Symphony Warning: The use statement with non-compound name 'MailChimp' has no effect

### ISSUE THREAD

**Issue by wdebusschere** [lewiswharf/mailchimp#22]
Symphony 2.6.7
Error when trying to access Symphony > Events

Symphony Warning: The use statement with non-compound name 'MailChimp' has no effect
event.mailchimp.php

**Comment by wdebusschere** [comment]
After adding manually the  /mailchimp/lib/mailchimp-api/MailChimp.php which was missing and changing line7 	use \MailChimp; to 	use \Drewm\MailChimp; it's working
https://github.com/drewm/mailchimp-api/tree/master

**Comment by nitriques** [comment]
Yeah same as #18

**Comment by nitriques** [comment]
Same php version ?

**Comment by wdebusschere** [comment]
Yes 5.6
